// Catalog of REAL programs for high schoolers, compiled Sep 2026 from curated lists
// (CollegeVine, Ladder, Veritas AI, Extern, Empowerly, College Transitions, StandOut) and then
// checked one-by-one against official pages. Programs with no verifiable official page were removed.
//
// Status is judged for Mason: 10th grade in 2026–27 (rising junior in summer 2027), turns 16 in Dec 2026,
// lives in San Diego County. Citizenship, gender and background aren't in the data block → "check".
//
// rate: a published/reported acceptance figure [percent, "source"] when one exists, otherwise a tier
// estimated from program type (clearly labeled in the app as an estimate):
//   entry 95 · open 90 · easy 65 · moderate 35 · selective 15 · competitive 8 · elite 3
//
// Row: [org, program, eligibility as published, location, mode, pay, typical deadline, official url,
//       field, kind, status, note, rate, about]

const RATE_TIERS = { entry: 95, open: 90, easy: 65, moderate: 35, selective: 15, competitive: 8, elite: 3 };

(() => {
  const rows = [
    // ---------------- San Diego County ----------------
    ["Palomar Health", "Pathmaker Internship", "Ages 16+", "Escondido, CA", "in-person", "Unpaid ($150 onboarding fee)", "Quarterly (Oct, Jan, Apr, Jul)", "https://www.palomarhealth.org/pathmaker-internship-program/", "health", "internship", "eligible", "Rotations open 4× a year — apply once you're 16.", "easy", "Hospital rotation program that lets teens see different departments at Palomar Medical Center."],
    ["Rady Children's Hospital", "FACES for the Future", "Sophomores through seniors", "San Diego, CA", "in-person", "Unpaid", "Varies", "https://sdhealthscholars.org/about-faces-for-the-future/", "health", "program", "eligible", "Confirm your school participates.", "moderate", ""],
    ["Banfield Pet Hospital", "NextVet", "High school students", "San Diego, CA", "in-person", "Paid ($15+/hr)", "Rolling", "https://jobs.banfield.com/NextVet", "health", "internship", "eligible", "", "moderate", "Paid job-style program in veterinary hospitals for students curious about animal care."],
    ["Scripps Research Translational Institute", "Student Research Internship (SURI)", "Ages 16+", "La Jolla, CA", "in-person", "Stipend varies", "Late March", "https://www.scripps.edu/science-and-medicine/translational-institute/education-and-training/student-research-internship/", "research", "research", "eligible", "", "selective", "Research internship on digital-medicine and data projects at Scripps' translational institute."],
    ["Scripps Research", "High School Student Research Education Program", "Ages 16+, 3.0+ GPA, San Diego County resident", "La Jolla, CA", "in-person", "Paid (~$5,040)", "March", "https://education.scripps.edu/k-12-outreach/ca-outreach/hs-internships/", "research", "research", "eligible", "Your GPA and county both qualify.", "selective", "Paid summer lab placement with a Scripps research team, open only to San Diego County students."],
    ["Salk Institute", "Heithoff-Brody High School Scholars", "Ages 16+, 2.75+ GPA, San Diego County, completed biology/chemistry", "La Jolla, CA", "in-person", "Paid ($17/hr)", "March", "https://www.salk.edu/about/education-outreach/programs/high-school-scholars/", "research", "research", "check", "Requires completed biology/chemistry — not in your data block.", "competitive", "Paid lab internship at the Salk Institute for San Diego County students."],
    ["J. Craig Venter Institute", "High School Internship", "Ages 16+", "La Jolla, CA", "in-person", "Paid (~$17.50/hr)", "Rolling", "https://www.jcvi.org/careers#internships", "research", "research", "eligible", "", "selective", "Paid genomics research internship in La Jolla."],
    ["U.S. Navy", "Science & Engineering Apprenticeship Program (SEAP)", "Grades 10–12, age 16+, U.S. citizen", "San Diego, CA + nationwide", "in-person", "Paid ($4,000–$4,500 stipend)", "Nov 1", "https://www.navalsteminterns.us/seap/", "tech", "internship", "eligible", "Deadline is usually Nov 1 — apply now. U.S. citizens only; confirm the age-16 cutoff date.", "competitive", "8-week paid summer apprenticeship at Navy labs — San Diego's is Naval Information Warfare Center Pacific.", "Aug"],
    ["U.S. House — Rep. Scott Peters", "San Diego District Office Internship", "High school seniors", "San Diego, CA", "in-person", "Paid (~$16.85/hr)", "Dec, Apr, Sep", "https://scottpeters.house.gov/internships", "gov", "internship", "soon", "Seniors only — apply in 2028–29.", "moderate", ""],
    ["Pacific Arts Movement", "Reel Voices", "High school students", "San Diego, CA", "in-person", "$500 scholarship", "April", "https://pacarts.org/reel-voices/", "arts", "program", "eligible", "", "moderate", "Documentary filmmaking program for San Diego teens."],
    ["Birch Aquarium (UC San Diego)", "Volunteer Program", "High school students", "La Jolla, CA", "in-person", "Unpaid", "Rolling", "https://aquarium.ucsd.edu/about/volunteer", "community", "volunteer", "eligible", "", "easy", ""],
    ["San Diego Natural History Museum", "Youth Internship Program", "Ages 16+, for school credit, biology course completed", "San Diego, CA", "in-person", "Unpaid", "Rolling", "https://www.sdnhm.org/join-and-give/volunteer/internships/", "research", "internship", "check", "Needs school credit and a completed biology course — not in your data block.", "easy", ""],
    ["Fleet Science Center", "Volunteer Program", "Ages 18+", "San Diego, CA", "in-person", "Unpaid", "Rolling", "https://www.fleetscience.org/volunteer", "community", "volunteer", "soon", "18+ only.", "easy", ""],
    ["San Diego County Sheriff's Department", "Student Worker", "Full-time high schoolers, 2.0+ GPA", "San Diego, CA", "in-person", "Paid", "Rolling", "https://www.joinsdsheriff.net/civilian-careers/student-workers/student-worker-19090504-undergraduate-graduate-tech-and-high-school", "gov", "internship", "eligible", "", "moderate", "Paid part-time county job for students (office and tech support roles)."],
    ["San Diego Sockers", "Internships", "High school students", "San Diego, CA", "in-person", "Unpaid", "Rolling", "https://www.sdsockers.com/internships", "business", "internship", "eligible", "Sports media/marketing — your photography fits.", "easy", "Pro indoor soccer team internships in game-day ops, media and marketing."],
    ["San Diego History Center", "Internships", "Ages 15+", "San Diego, CA", "in-person", "Unpaid", "Jan 15, Apr 30, Sep 8", "https://sandiegohistory.org/internships/", "arts", "internship", "eligible", "", "easy", ""],
    ["San Diego Museum of Art", "Teen Council", "Grades 9–12", "San Diego, CA", "in-person", "Unpaid", "Varies", "https://www.sdmart.org/teens/", "arts", "program", "eligible", "", "moderate", ""],
    ["La Jolla Playhouse", "Internships", "Recent high school graduates", "La Jolla, CA", "in-person", "Paid (minimum wage)", "July", "https://lajollaplayhouse.org/who-we-are/get-involved/internships/", "arts", "internship", "soon", "After you graduate (2029).", "moderate", ""],
    ["DPR Construction", "Build Up High School Internship", "Rising juniors/seniors and recent grads", "San Diego, CA", "in-person", "Paid", "April", "https://www.dpr.com/build-up-high-school-internship", "tech", "internship", "eligible", "You're a rising junior in summer 2027.", "selective", "Paid summer internship on real construction projects with a national builder."],
    ["Media Arts Center San Diego", "Internship", "High school students", "San Diego, CA", "in-person", "Unpaid", "Varies", "https://mediaartscenter.org/home/education/internships/", "arts", "internship", "eligible", "Media/photo work — fits your portfolio.", "easy", ""],
    ["San Diego Zoo Wildlife Alliance", "Internships", "High school students", "San Diego, CA", "in-person", "Paid/unpaid", "Nov–Jan", "https://sandiegozoowildlifealliance.org/jobs/internships", "research", "internship", "eligible", "Your animal photography award is relevant.", "selective", "12-week summer internships at the Zoo and Safari Park."],
    ["Sharp Memorial Hospital", "High School Internship", "Ages 15+, 100-hour minimum", "San Diego, CA", "in-person", "Unpaid", "Spring", "https://www.sharp.com/volunteers/memorial", "health", "internship", "eligible", "", "easy", ""],
    ["San Diego Air & Space Museum", "Volunteer Program", "High school students", "San Diego, CA", "in-person", "Unpaid", "Rolling", "https://sandiegoairandspace.org/support/volunteer-at-the-museum", "community", "volunteer", "eligible", "", "open", ""],
    ["San Diego Public Library", "Teen Volunteer", "High school students", "San Diego, CA", "in-person", "Unpaid", "Rolling", "https://www.sandiego.gov/volunteer-program/opportunities/communityservices/library", "community", "volunteer", "eligible", "", "open", ""],
    ["City of San Diego", "Department Volunteer Internships", "High school students (varies by department)", "San Diego, CA", "in-person", "Varies", "Year-round", "https://app.betterimpact.com/PublicOrganization/a267e329-b05d-489d-a0ef-2f1c9cfd48cc/1", "gov", "internship", "eligible", "", "easy", ""],
    ["Air Force Research Laboratory", "AFRL Scholars", "Ages 16+, 3.0+ GPA, U.S. citizen", "AFRL sites nationwide", "in-person", "Paid (~$500/week)", "Jan 10", "https://afrlscholars.usra.edu/scholarsprogram/", "tech", "internship", "check", "U.S. citizens only, and you must live near an AFRL site.", "competitive", ""],
    ["Alliance of Chinese Americans San Diego", "API Summer Journalism Internship", "High schoolers of Asian/Pacific Islander descent, San Diego County", "San Diego, CA (hybrid)", "hybrid", "$250", "June 1", "https://www.acasandiego.org/2025-82038203api-journalism-internship.html", "arts", "internship", "check", "For API-descent students — your data block doesn't say.", "moderate", ""],
    ["Sanford Burnham Prebys", "SPARK", "Ages 16+, California high school student", "La Jolla, CA", "in-person", "Paid (CIRM-funded)", "April 1", "https://sbpdiscovery.org/education/internships/", "research", "research", "eligible", "", "competitive", "Paid stem-cell research internship funded by California's stem cell agency."],
    ["LaunchX", "San Diego In-Person Entrepreneurship Program", "High school students (ages 14–18)", "San Diego, CA (UC San Diego)", "in-person", "Fee (~$11,495; aid available)", "Rolling", "https://www.launchx.com/programs/san-diego-in-person-entrepreneurship", "business", "program", "eligible", "Program, not a job — you build a real startup.", "moderate", "4-week full-time startup program: teams launch a real company. Online version starts around $6,495."],

    // ---------------- California ----------------
    ["California Science Center", "Community Teen Interns", "Grades 10–12, 2.0+ GPA, LA-area preferred", "Los Angeles, CA", "in-person", "Paid", "Varies", "https://californiasciencecenter.org/programs/community-teen-interns", "community", "internship", "check", "LA-area residents preferred.", "moderate", ""],
    ["Kaiser Permanente", "KP Launch", "Ages 16–19, Northern California", "Northern California", "in-person", "Paid (~$24/hr)", "January", "https://about.kaiserpermanente.org/community-health/education/career-launch-programs", "health", "internship", "ineligible", "Northern California residents only.", "selective", ""],
    ["Stanford Medicine", "SIMR (Stanford Institutes of Medicine Summer Research)", "Juniors/seniors, 16+, U.S. citizen/PR", "Stanford, CA", "in-person", "Free", "Late fall", "https://med.stanford.edu/simr.html", "research", "research", "soon", "Apply in fall 2027 as a junior.", [3, "reported under 3%"], "8-week biomedical research placement in Stanford labs."],
    ["UC Santa Barbara", "Research Mentorship Program (RMP)", "10th–11th grade, 3.8+ GPA", "Santa Barbara, CA", "in-person", "See site (aid available)", "March", "https://www.summer.ucsb.edu/pre-college/research-mentorship-program", "research", "research", "eligible", "You're in 10th with a 4.0 — strong match.", "selective", "6-week program where you do an original research project with a UCSB mentor."],
    ["Stanford AIMI", "Summer Research Internship (AI in medicine)", "Ages 14+, U.S. residents", "Remote / Stanford, CA", "remote", "Fee (~$850, aid available)", "Late Feb", "https://aimi.stanford.edu/education/summer-research-internship", "tech", "research", "eligible", "AI + Python — fits your projects.", "moderate", "Virtual program on AI in healthcare with Stanford researchers."],
    ["Stanford SHTEM", "SHTEM Summer Internships", "High school juniors/seniors, 14+", "Remote", "remote", "Free ($50 app fee, waivers)", "March", "https://compression.stanford.edu/outreach/shtem-summer-internships-high-schoolers-and-community-college-students", "tech", "research", "check", "Listed for juniors/seniors — confirm whether rising juniors qualify.", "selective", ""],
    ["UC Berkeley Haas", "Business Academy for Youth (B-BAY)", "Grades 10–12", "Berkeley, CA", "in-person", "Fee (~$6,050 CA residents)", "Spring", "https://haas.berkeley.edu/ibsi/about-the-institute/blog/posts/delivering-entrepreneurship-training-to-high-schoolers-berkeley-haass-business-academy-for-youth-b-bay-continues-to-thrive/", "business", "program", "eligible", "", "moderate", "2-week Haas program: finance, accounting, negotiation, and building a startup concept. About 50 seats in the entrepreneurship track."],
    ["UCLA", "Introduction to Investments Summer Institute", "High school students who can commute to UCLA", "Los Angeles, CA", "in-person", "Fee (scholarships available)", "June", "https://summer.ucla.edu/program/introduction-to-investments/", "finance", "program", "check", "Session A requires a daily commute to UCLA.", "easy", "3-week course from UCLA Economics: stocks, bonds, the Fed, valuation, hedge funds, careers in finance. Earns 4 units of UCLA credit."],
    ["Stanford Pre-Collegiate Studies", "Summer Institutes (online)", "Grades 8–11", "Online", "remote", "Fee (aid available)", "Winter", "https://summerinstitutes.spcs.stanford.edu/", "research", "program", "eligible", "", "moderate", "75+ online courses (AI, engineering, math…). Ungraded, no credit."],
    ["City of Hope", "Eugene & Ruth Roberts Summer Student Academy", "High school and university students", "Duarte, CA", "in-person", "Paid ($4,000 stipend)", "Mid-March", "https://robertsacademy.cityofhope.org/", "research", "research", "check", "In-person near LA; confirm the minimum age.", [2, "82 of ~2,100 applicants accepted (2025)"], "10 weeks full-time on a biomedical research team.", "Mid-Jan"],
    ["Sandia National Laboratories", "Student Intern Program", "Ages 16+, full-time high school, 3.0+ GPA", "Livermore, CA / Albuquerque, NM", "in-person", "Paid", "Varies", "https://www.sandia.gov/careers/career-possibilities/students-and-postdocs/internships-co-ops/", "tech", "internship", "check", "Must live near Livermore or Albuquerque.", "competitive", ""],
    ["Meta", "Meta Summer Academy", "Sophomores, residents of East Palo Alto / Belle Haven / Redwood City", "Menlo Park, CA", "in-person", "Paid", "Feb", "https://metasummeracademy.com/", "tech", "internship", "ineligible", "Local residents only.", "selective", ""],
    ["CLA (CliftonLarsonAllen)", "High School Internship Program", "Juniors/seniors, ages 16–18", "Multiple U.S. offices", "in-person", "Paid", "Early spring", "https://www.claconnect.com/en/careers/high-school-internship", "finance", "internship", "check", "Confirm whether rising juniors count and if there's an office near you.", "selective", ""],

    // ---------------- National: research / STEM ----------------
    ["NASA", "Neurodiversity Network (N3) Internship", "Ages 16+, neurodivergent high school students", "Remote", "remote", "Paid ($1,000)", "March", "https://www.nasa.gov/learning-resources/internship-programs/", "research", "research", "check", "For neurodivergent students.", "competitive", ""],
    ["NASA / UT Austin", "STEM Enhancement in Earth Science (SEES)", "Ages 16+, grades 10–11, U.S. citizen", "Remote + Austin, TX", "hybrid", "Fee (~$2,000, scholarships)", "Feb", "https://csr.utexas.edu/education-outreach/high-school-internships/sees/", "research", "research", "eligible", "U.S. citizens only. You're in the right grade now.", "competitive", "Nationally competitive NASA internship: remote modules, then 2 weeks on-site in Austin analyzing satellite data with NASA experts."],
    ["NASA GISS", "Climate Change Research Initiative", "U.S. high schoolers, juniors/seniors preferred", "New York, NY / Greenbelt, MD", "in-person", "Unpaid", "Varies", "https://www.giss.nasa.gov/edu/ccri/", "research", "research", "check", "Juniors/seniors preferred; hosted in NYC or Maryland.", "competitive", "Year-long climate research teams mentored by NASA scientists."],
    ["Smithsonian National Museum of Natural History", "Summer High School Internship", "Ages 15–18, must commute from DC/MD/VA", "Washington, DC", "in-person", "Paid stipend", "March 20", "https://naturalhistory.si.edu/education/youth-programs/high-school-internship-program", "research", "internship", "ineligible", "Interns must live within commuting distance of DC.", "selective", ""],
    ["Smithsonian Center for Folklife", "Folklife Internships", "Ages 14+", "Remote", "remote", "Paid", "Varies", "https://internships.si.edu/opportunity/internships-center-folklife-and-cultural-heritage", "arts", "internship", "eligible", "", "selective", ""],
    ["Smithsonian Science Education Center", "SSEC Internships", "Ages 16+", "Remote / Washington, DC", "hybrid", "Unpaid", "Feb, July, Oct", "https://ssec.si.edu/smithsonian-science-education-center-internship-program", "research", "internship", "eligible", "", "moderate", ""],
    ["Smithsonian Institution", "Summer Internships (all museums)", "Ages 15–18", "Multiple", "hybrid", "Paid stipend", "March", "https://internships.si.edu/opportunities", "research", "internship", "eligible", "Many listings require living near DC — filter by location on the site.", "selective", ""],
    ["MIT / Center for Excellence in Education", "Research Science Institute (RSI)", "Rising seniors, 15+", "Cambridge, MA", "in-person", "Fully funded", "January", "https://www.cee.org/programs/rsi", "research", "research", "soon", "Apply as a junior (2027–28).", [2, "about 100 admitted a year, ~2.1% (2026)"], "The most selective STEM research program for high schoolers — 6 weeks at MIT."],
    ["Stony Brook University", "Simons Summer Research Program", "Rising seniors, school nomination", "Stony Brook, NY", "in-person", "Stipend", "February", "https://www.stonybrook.edu/simons/", "research", "research", "soon", "Apply as a junior.", [5, "reported ~4–5%"], ""],
    ["Broad Institute", "Broad Summer Scholars (BSSP)", "Rising seniors (Massachusetts)", "Cambridge, MA", "in-person", "Paid", "Jan–Feb", "https://www.broadinstitute.org/bssp", "research", "research", "ineligible", "Massachusetts students.", "elite", ""],
    ["Boston University", "RISE Internship", "Rising seniors", "Boston, MA", "in-person", "Fee (tuition-based)", "Mid-Feb", "https://www.bu.edu/summer/high-school-programs/rise/", "research", "research", "soon", "Apply as a junior.", "selective", ""],
    ["Fermilab", "TARGET Internship", "Illinois sophomores/juniors, 3.0+ GPA", "Batavia, IL", "in-person", "Paid (~$16/hr)", "February", "https://internships.fnal.gov/", "research", "internship", "ineligible", "Illinois students.", "selective", ""],
    ["Princeton University", "Laboratory Learning Program", "Ages 16–17", "Princeton, NJ", "in-person", "Free", "Feb–Mar", "https://scienceoutreach.princeton.edu/laboratory-learning-program", "research", "research", "check", "In-person in NJ; some listings say NJ students only.", "competitive", ""],
    ["Microsoft", "Discovery Program", "Graduating seniors near Redmond, WA or Atlanta", "Redmond, WA / Atlanta, GA", "in-person", "Paid (~$26/hr)", "Early March", "https://careers.microsoft.com/v2/global/en/discoveryprogram", "tech", "internship", "ineligible", "Local graduating seniors only.", "competitive", ""],
    ["Girls Who Code", "Summer Immersion Program", "Girls and non-binary students, rising 9th–11th", "Remote", "remote", "Free", "March", "https://girlswhocode.com/programs/summer-immersion-program", "tech", "program", "check", "For girls and non-binary students.", "moderate", ""],
    ["Lockheed Martin", "High School Internship", "Ages 16+, near an LM facility, not a graduating senior", "Multiple U.S. sites", "in-person", "Paid", "Fall", "https://www.lockheedmartin.com/en-us/careers/candidates/students-early-careers/high-school.html", "tech", "internship", "check", "Must live near a Lockheed Martin facility.", "competitive", ""],
    ["MIT Lincoln Laboratory", "LLRISE", "Completing junior year", "Lexington, MA", "in-person", "Free", "March", "https://www.ll.mit.edu/outreach/llrise", "tech", "program", "soon", "Apply as a junior.", "competitive", ""],
    ["MIT", "Beaver Works Summer Institute (BWSI)", "High schoolers with coding experience (mostly rising seniors)", "Cambridge, MA / online", "hybrid", "Free", "Spring", "https://beaverworks.ll.mit.edu/CMS/bw/bwsi", "tech", "program", "soon", "Mostly rising seniors.", "competitive", ""],
    ["MIT", "MITES Summer", "High school juniors", "Cambridge, MA", "in-person", "Free", "February", "https://mites.mit.edu/discover-mites/mites-summer/", "tech", "program", "soon", "Apply as a junior.", [4, "reported 3–5%"], ""],
    ["NSA", "High School Work Study", "Juniors near NSA facilities", "MD, TX, GA, HI, CO", "in-person", "Paid", "October", "https://www.intelligencecareers.gov/nsa/students-and-internships", "tech", "internship", "ineligible", "Must live near an NSA site.", "competitive", ""],
    ["NIH", "Summer Internship Program (HS-SIP)", "Seniors, 16+, U.S. citizen/PR", "Bethesda, MD", "in-person", "Paid stipend", "March", "https://www.training.nih.gov/programs/sip", "research", "research", "soon", "Senior year.", "competitive", ""],
    ["Fred Hutch Cancer Center", "Summer High School Internship (SHIP)", "Washington State seniors", "Seattle, WA", "in-person", "Paid", "March", "https://www.fredhutch.org/en/education-training/high-school-students/summer-high-school-internship-program.html", "research", "research", "ineligible", "Washington State students.", "competitive", ""],
    ["Johns Hopkins", "Internship in Brain Sciences (JHIBS)", "Rising juniors/seniors; some years limited to groups underrepresented in STEM", "Remote", "remote", "Unpaid", "March 1", "https://www.hopkinsmedicine.org/neurology-neurosurgery/research/jhu-nimh/jhibs", "research", "research", "check", "Confirm the current eligibility (may target underrepresented groups).", "competitive", ""],
    ["Johns Hopkins APL", "ASPIRE", "Rising juniors/seniors, U.S. citizen, living in select MD/VA/DC areas", "Laurel, MD", "in-person", "Unpaid", "Varies", "https://www.jhuapl.edu/education/stem-outreach/aspire", "tech", "internship", "ineligible", "Local residents only.", [18, "reported ~15–20%"], ""],
    ["U.S. Senate", "Senate Page Program", "Juniors, 16–17, 3.0+ GPA, Senator sponsorship", "Washington, DC", "in-person", "Paid", "Varies by Senator", "https://www.senate.gov/reference/Pages/page_program.htm", "gov", "internship", "soon", "Junior year, with a Senator's sponsorship.", "elite", ""],
    ["U.S. Army", "AEOP High School Apprenticeships", "U.S. high school students (some sites have grade/age rules)", "Army labs nationwide", "in-person", "Stipend", "Sep–Mar", "https://www.usaeop.com/program/high-school-apprenticeships/", "research", "research", "eligible", "Check for a site near San Diego.", "selective", "Paid summer research apprenticeships at Army-funded labs and universities."],
    ["U.S. Department of State", "Pathways Internship", "Ages 16+, U.S. citizen, 2.0+ GPA", "Remote / multiple", "hybrid", "Paid", "Year-round", "https://careers.state.gov/interns-fellows/pathways-programs/", "gov", "internship", "eligible", "U.S. citizens only; 16+.", "competitive", ""],
    ["Bloomberg Philanthropies", "Bloomberg Arts Internship", "Rising seniors at public schools in participating cities", "9 U.S. cities", "in-person", "Paid ($20+/hr)", "Feb–Mar", "https://www.bloomberg.org/arts/strengthening-local-arts-organizations/bloomberg-arts-internship/", "arts", "internship", "soon", "Rising seniors — and San Diego must be a participating city.", "selective", ""],
    ["Metropolitan Museum of Art", "Teen Internship Program", "10th–11th grade, NY/NJ/CT", "New York, NY", "in-person", "Paid ($1,100)", "February", "https://www.metmuseum.org/join-and-give/internships", "arts", "internship", "ineligible", "NY/NJ/CT students.", "selective", ""],
    ["PBS NewsHour", "Student Reporting Labs", "High school students", "Remote (through partner schools)", "remote", "Varies", "Spring", "https://studentreportinglabs.org/", "arts", "program", "check", "Runs through partner schools/teachers.", "moderate", ""],
    ["California Academy of Sciences", "Careers in Science (CiS)", "9th–10th grade SFUSD students", "San Francisco, CA", "in-person", "Paid", "April", "https://www.calacademy.org/careers-in-science", "research", "internship", "ineligible", "SFUSD students only.", "selective", ""],
    ["Seaside Sustainability", "Internships / Green Scholars", "All high school students", "Remote", "remote", "Free", "Rolling", "https://www.seasidesustainability.org/internships", "community", "internship", "eligible", "", "open", ""],
    ["Texas Tech University", "Anson L. Clark Scholars", "Juniors and seniors", "Lubbock, TX", "in-person", "Paid stipend", "Late Feb", "https://www.depts.ttu.edu/honors/academicsandenrichment/affiliatedandhighschool/clarks/", "research", "research", "soon", "Apply as a junior.", "elite", ""],
    ["NIST", "Summer High School Intern Program (SHIP)", "Completed junior year, 3.0+ GPA", "Gaithersburg, MD / Boulder, CO", "in-person", "Varies", "February", "https://www.nist.gov/iaao/academic-affairs-office/high-school-students-ship/ship-research", "research", "research", "soon", "After junior year.", "competitive", ""],
    ["MITRE", "Nationwide High School Student Program", "Ages 14+, 3.0+ GPA", "MITRE sites", "in-person", "Paid", "Varies", "https://careers.mitre.org/us/en/nationwide-high-school-student-program", "tech", "internship", "check", "Must be near a MITRE site.", "selective", ""],
    ["Carnegie Mellon", "Computer Science Scholars (CSS)", "Sophomores, 16+", "Pittsburgh, PA", "in-person", "Free (grant-funded)", "March 1", "https://www.cmu.edu/pre-college/academic-programs/computer-science-scholars.html", "tech", "program", "eligible", "You're a sophomore now — apply this cycle.", "competitive", "Free CS program at CMU for rising juniors."],
    ["Forage", "Virtual Work Experience Programs", "Anyone, no experience required", "Online", "remote", "Free", "Anytime", "https://www.theforage.com/", "business", "virtual", "eligible", "Self-paced company simulations — you can start today.", "entry", "Free, self-paced job simulations built by real companies. Finish one and you can list it on your resume."],
    ["JPMorgan Chase", "Virtual Job Simulations (via Forage)", "Anyone", "Online", "remote", "Free", "Anytime", "https://www.theforage.com/", "finance", "virtual", "eligible", "Free, self-paced — you can list completion on a resume after you finish it.", "entry", "JPMorgan-built finance and software simulations on Forage."],
    ["University of Chicago", "Data Science Institute Summer Lab", "Freshmen through seniors", "Chicago, IL", "in-person", "Paid (~$5,600)", "January", "https://datascience.uchicago.edu/education/summerlab/", "tech", "research", "check", "In-person Chicago; mostly local students.", "competitive", ""],
    ["Kode With Klossy", "Coding Camps", "Ages 13–18, women and gender-expansive teens", "Remote / varies", "remote", "Free", "March", "https://www.kodewithklossy.com/camp", "tech", "program", "check", "For women and gender-expansive teens.", "moderate", ""],
    ["Spark SMP", "Summer Mentorship Program", "High school students (Seattle area), U.S. citizens/PR", "Seattle, WA / virtual", "hybrid", "Free; some stipends", "May", "https://www.sparksmp.org/", "tech", "research", "check", "Seattle-area focus — confirm remote projects.", "selective", ""],
    ["theCoderSchool", "UpCode Internship", "Ages 15–18 with 3+ years of coding", "theCoderSchool locations", "in-person", "See site", "Opens Oct 1", "https://www.thecoderschool.com/upcode-internship/", "tech", "internship", "check", "Needs 3+ years of coding — your data shows 2025–present.", "moderate", "Teams of high-school coders build a real product for a client."],
    ["Immerse Education", "Software Development & AI Summer School", "Ages 15–18", "Online / Boston / UK", "hybrid", "Fee", "Rolling", "https://www.immerse.education/software-development-ai-summer-school/", "tech", "program", "eligible", "Paid course.", "open", "1-to-1 tutoring from Oxbridge/Ivy tutors on software and AI. No prior knowledge required."],
    ["Inspirit AI", "AI Scholars Live Online", "High school students", "Online", "remote", "Fee", "Rolling", "https://www.inspiritai.com/liveonline", "tech", "program", "eligible", "Paid course.", "open", "10-session (25-hour) AI bootcamp; you build an AI project in Python with Stanford/MIT grad-student instructors."],

    // ---------------- Remote ----------------
    ["Building-U", "High School Internship", "Grades 9–12", "Remote", "remote", "Unpaid", "Rolling (email internships@building-u.com)", "https://building-u.com/opportunities/internships/", "business", "internship", "eligible", "", "easy", "Year-round online internship on student-led teams: web dev, data analytics, digital marketing, business development."],
    ["EnergyMag", "Research / Journalism Internship", "Sophomores–seniors, 3.25+ GPA", "Remote", "remote", "Unpaid", "Rolling", "https://energymag.net/internships/", "research", "internship", "eligible", "", "easy", ""],
    ["Foreign Policy Research Institute", "High School Internship", "High schoolers with strong writing; authorized to work in U.S.", "Remote", "remote", "Unpaid (need-based stipends)", "Dec, Mar, Jul", "https://www.fpri.org/", "gov", "internship", "eligible", "", "moderate", ""],
    ["Polygence", "Core Research Program", "High school students", "Remote", "remote", "Fee (aid available)", "Monthly", "https://www.polygence.org/core-program", "research", "research", "eligible", "Paid mentorship — you do your own project.", "open", "10 one-on-one sessions with an expert mentor on a project you choose — papers, apps, prototypes. Can earn UC Irvine credit."],
    ["Lumiere Education", "Research Scholar Program", "High school students, GPA 3.3+", "Remote", "remote", "Fee (aid available)", "Rolling", "https://www.lumiere-education.com/", "research", "research", "eligible", "Paid mentorship. Rate isn't published.", "moderate", "One-on-one research mentorship with a PhD mentor; application plus interview."],
    ["George Mason University", "Aspiring Scientists Summer Internship (ASSIP)", "Ages 15+ remote (16+ wet-lab), 2.8+ GPA; some sources say juniors/seniors", "Remote / Fairfax, VA", "hybrid", "Unpaid ($25 fee)", "Feb 1", "https://science.gmu.edu/assip", "research", "research", "check", "Confirm whether sophomores/rising juniors can apply.", "selective", ""],
    ["UT Southwestern", "Inspiring Careers in Mental Health", "Rising 10th–12th graders in the U.S.", "Remote", "remote", "Unpaid", "Early Feb", "https://www.utsouthwestern.edu/education/medical-school/departments/psychiatry/education-and-training/inspiring-careers.html", "health", "internship", "eligible", "", "moderate", ""],
    ["Dartmouth-Hitchcock (Levy Lab)", "EDIT AI Summer Internship", "High schoolers with prior CS coursework/experience", "Remote", "remote", "Unpaid", "April 15", "https://jlevy44.github.io/levylab/opportunities/", "tech", "research", "eligible", "AI research — your Python projects count as experience.", "selective", "Remote AI-in-medicine research with a Dartmouth lab."],
    ["American Psychological Association", "APA Internships", "U.S.-eligible workers; under 18 needs a DC work permit", "Remote", "remote", "Paid/unpaid", "Rolling", "https://www.apa.org/about/apa-jobs/internships", "health", "internship", "check", "Under-18s need a DC work permit.", "selective", ""],

    // ---------------- Finance & business ----------------
    ["1435 Capital Management", "Venture Analyst Internship", "Rising juniors/seniors, 16+", "Princeton, NJ (hybrid)", "hybrid", "Paid", "Early April", "https://app.dover.com/apply/1435%20Capital%20Management%20LLC/8ccf0267-2ff5-4800-b769-149b8a1e8aad/?rs=76643084", "finance", "internship", "eligible", "Investing-focused and you're a rising junior in 2027 — strong fit.", "competitive", "Venture/investing analyst work at a small investment firm — hybrid, so remote work is possible."],
    ["Federal Reserve Bank of Boston", "Today's Interns, Tomorrow's Professionals (TIP)", "Boston Public Schools, completed sophomore year", "Boston, MA", "in-person", "Paid", "Early spring", "https://www.bostonfed.org/community-development/expanding-employment-opportunities/todays-interns-tomorrows-professionals.aspx", "finance", "internship", "ineligible", "Boston Public Schools.", "selective", ""],
    ["Dartmouth College", "Finance: Investing & Market Insights", "Ages 13+", "Online", "remote", "Fee (~$1,895, scholarships)", "Rolling", "https://precollegeonline.dartmouth.edu/finance", "finance", "program", "eligible", "Course, not a job.", "open", "20–30 hours online: markets, risk vs. reward, valuing stocks and bonds, reading financial statements, capstone project. Dartmouth certificate."],
    ["University of Tennessee Haslam", "Accounting & Information Management (AIM) Academy", "Sophomores, 3.0+ GPA; for underrepresented, first-gen, or free/reduced-lunch students", "Knoxville, TN", "in-person", "Free", "Mid-Dec – Mar 31", "https://haslam.utk.edu/access/accounting-and-information-management-aim-academy", "finance", "program", "check", "Aimed at underrepresented / first-gen / FRL students.", "moderate", "Free 6-day residential program in accounting, finance and entrepreneurship, sponsored by Crowe LLP."],
    ["LEADing for Life", "Morgan Stanley JumpStart Scholars in Finance", "High school seniors", "Virtual", "remote", "Free", "~May", "https://www.leadingforlife.org/msjumpstart/index.jsp", "finance", "program", "soon", "Seniors only.", "selective", "5-month virtual finance program taught by Morgan Stanley associates, ending in a case competition."],
    ["Federal Reserve System", "High School Fed Challenge", "Grades 9–12, school teams of 3–8", "National (via your school)", "remote", "Free", "Team registration ~Feb", "https://www.federalreserveeducation.org/news/2026-high-school-fed-challenge-registration", "finance", "competition", "eligible", "Needs a teacher advisor to register a team.", "entry", "Economics research-and-writing competition; one team per school."],
    ["Wharton (UPenn)", "Global High School Investment Competition", "Grades 9–12, teams of 4–6 with a teacher", "Online (finale in Philadelphia)", "remote", "Free", "Registration ~summer", "https://globalyouth.wharton.upenn.edu/competitions/investment-competition/", "finance", "competition", "eligible", "Investing competition — directly uses your trading skills.", "entry", "10 weeks managing a simulated $500,000 portfolio for a client case; top 10 teams go to Wharton."],
    ["Council for Economic Education", "National Personal Finance Challenge", "Grades 9–12", "State rounds → nationals", "in-person", "Free", "Varies by state", "https://www.councilforeconed.org/programs/for-students/national-personal-finance-challenge/", "finance", "competition", "eligible", "", "entry", "15,000+ students compete on earning, saving, investing, credit and risk."],
    ["Council for Economic Education", "National Economics Challenge", "High school teams of 4", "State rounds → nationals", "in-person", "Free", "Varies by state", "https://www.councilforeconed.org/programs/for-students/national-economic-challenge/", "finance", "competition", "eligible", "", "entry", "11,000+ students; micro, macro, international economics and current events."],
    ["SIFMA Foundation", "The Stock Market Game", "Grades 4–12", "Online", "remote", "Free in many states", "Each session", "https://www.stockmarketgame.org/", "finance", "competition", "eligible", "Through a teacher.", "entry", "Manage a virtual $100,000 portfolio of stocks and bonds."],
    ["DECA", "Business Finance Series", "DECA members", "District → International", "in-person", "Membership dues", "Via chapter", "https://www.deca.org/compete/business-finance-series", "finance", "competition", "check", "Needs a DECA chapter at your school.", "entry", "Role-play finance events: planning, reports, data-driven business decisions."],
    ["FBLA", "Securities & Investments", "FBLA members", "Region → National", "remote", "Membership dues", "Dec 1 membership", "https://www.fbla.org/competitive-events/securities-investments/", "finance", "competition", "check", "Needs an FBLA chapter at your school.", "entry", "100-question test on stocks, bonds, funds, portfolios and risk."],
    ["Wharton (UPenn)", "Global Youth — Essentials of Finance", "Grades 9–11", "Philadelphia, PA", "in-person", "Fee (~$7,599, scholarships)", "Late Jan / early Apr", "https://globalyouth.wharton.upenn.edu/programs-courses/essentials-of-finance/", "finance", "program", "eligible", "", "moderate", "2-week residential course by Prof. Michael Roberts: time value of money, DCF, valuation, venture capital."],
    ["Wharton (UPenn)", "Leadership in the Business World (LBW)", "Current 11th graders", "Philadelphia, PA", "in-person", "Fee (~$9,999, scholarships)", "Late Jan / early Apr", "https://globalyouth.wharton.upenn.edu/on-campus-programs/", "business", "program", "soon", "11th grade only.", "selective", ""],
    ["Harvard Summer School", "Pre-College Program", "Rising juniors/seniors, 16+ by late June", "Cambridge, MA", "in-person", "Fee (~$6,100)", "Jan–Apr", "https://summer.harvard.edu/high-school-programs/pre-college-program/", "business", "program", "eligible", "Summer 2027: you'll be a rising junior and 16.", "moderate", "2-week residential program taking one non-credit college course (~30 to choose from)."],
    ["Yale Young Global Scholars", "Politics, Law & Economics", "Ages 16–18, sophomores or juniors", "New Haven, CT", "in-person", "Fee ($6,500, up to 100% aid)", "Oct 15 (early) / Jan 7", "https://globalscholars.yale.edu/application-deadlines", "finance", "program", "eligible", "Sophomores can apply — early deadline is mid-October.", [18, "~1,800 admitted of ~10,000 applicants (2024)"], "2-week Yale program with lectures, seminars and a capstone; big need-based aid."],
    ["Columbia University", "Pre-College Programs", "Grades 9–12", "New York, NY / online", "hybrid", "Fee (scholarships)", "Rolling", "https://precollege.sps.columbia.edu/", "business", "program", "eligible", "", "easy", ""],
    ["NYU", "Precollege — Summer @ Stern", "Rising juniors and seniors", "New York, NY", "in-person", "Fee", "Rolling", "https://www.nyu.edu/admissions/high-school-and-middle-school-programs/high-school-programs/nyu-precollege/explore-precollege.html", "finance", "program", "eligible", "Rising junior in 2027. Two-step admission (NYU Precollege, then Stern).", "moderate", "6-week summer at NYU Stern: accounting, finance, economics, marketing."],
    ["Georgetown University", "Business & Leadership Academy", "High school students", "Washington, DC", "in-person", "Fee", "Rolling", "https://summer.georgetown.edu/programs/SHS34/business-leadership-academy/", "business", "program", "eligible", "", "easy", ""],
    ["Michigan Ross", "Summer Business Academy", "Rising seniors, 3.0+ GPA", "Ann Arbor, MI", "in-person", "Fee ($5,500, scholarships)", "Mid-Jan", "https://michiganross.umich.edu/undergraduate/summer-business-academy", "business", "program", "soon", "Rising seniors.", "selective", ""],
    ["Fordham Gabelli", "Finance Institute: Wall Street in the Classroom", "Grades 10–12", "New York, NY / remote (hybrid)", "hybrid", "Fee (~$1,100; $100 deposit)", "Priority April 1", "https://www.fordham.edu/gabelli-school-of-business/academic-programs-and-admissions/undergraduate-programs/specialty-programs/summer-business-programs/finance-institute-wall-street-in-the-classroom/", "finance", "program", "eligible", "Can attend remotely.", "easy", "Markets, stocks and bonds, alternative investments, risk management; guest speakers from finance firms."],
    ["Wake Forest School of Business", "Finance & Investing Institute", "Rising sophomores through incoming college freshmen", "Winston-Salem, NC", "in-person", "Fee (~$2,800, scholarships)", "Rolling (fills early)", "https://immersion.summer.wfu.edu/on-campus-institutes/finance-and-investing/", "finance", "program", "eligible", "", "easy", "Investing approaches, fundamental analysis and finance careers with Wake Forest faculty."],
    ["Babson College", "Arthur M. Blank School Summer Program", "Rising juniors/seniors, 16+", "Wellesley, MA / online", "hybrid", "Fee (aid available)", "Priority Mar 15", "https://www.babson.edu/summer-at-babson/high-school-learners/the-arthur-m-blank-school-summer-program/", "business", "program", "eligible", "", "easy", "50+ hands-on courses in entrepreneurship, AI, business and marketing."],
    ["Indiana University Kelley", "Business Is Global (BIG)", "Rising sophomores–seniors", "Bloomington, IN", "in-person", "Scholarships available", "Spring", "https://kelley.iu.edu/faculty-research/centers-institutes/international-business/programs-initiatives/business-is-global.html", "business", "program", "eligible", "", [28, "57 selected from 200+ applicants (2025)"], "2-week program on international business, language and culture."],
    ["NFTE", "Entrepreneurship Programs / BizCamps", "Ages 11–24", "25+ states / online", "hybrid", "Varies", "Varies", "https://nfte.com/programs/all-programs/", "business", "program", "eligible", "", "open", "Entrepreneurship courses and 50–90 hour summer BizCamps."],
    ["Goldman Sachs", "Possibilities Summit", "High school juniors from underrepresented backgrounds", "Multiple", "in-person", "Free", "February", "https://www.goldmansachs.com/careers/students/programs/", "finance", "program", "soon", "Juniors; for underrepresented backgrounds.", "selective", ""],
    ["Chicago Summer Business Institute", "CSBI", "Chicago 10th–11th graders, 3.0+ GPA, income limit", "Chicago, IL", "in-person", "Paid", "Feb–Mar", "https://www.chicagosbi.org/", "finance", "internship", "ineligible", "Chicago students.", "selective", ""],
    ["Economic Awareness Council", "On the Money Summer Internship", "HS seniors / college students (Chicago)", "Chicago, IL", "hybrid", "Paid (~$17/hr)", "May 29", "https://www.econcouncil.org/on-the-money", "finance", "internship", "ineligible", "Chicago; seniors.", "selective", ""],
    ["U.S. Department of the Treasury", "Headquarters Student Internship", "High school students", "Washington, DC", "in-person", "Unpaid", "December", "https://home.treasury.gov/about/careers-at-treasury/studentinternship-programs/headquarters-student-internship-program", "gov", "internship", "check", "In-person Washington, DC.", "selective", ""],
    ["YEP KC", "Young Entrepreneurs Program", "Completing junior/senior year, Kansas City", "Kansas City, MO", "in-person", "Paid + scholarship", "Feb 1", "https://yepkc.org/", "business", "internship", "ineligible", "Kansas City area.", "selective", ""],
    ["Air Academy Credit Union", "High School Internship", "Grades 11–12, 16+", "Colorado Springs, CO", "in-person", "Paid", "April", "https://www.aacu.com/learn/about/internship-program.html", "finance", "internship", "ineligible", "Colorado Springs.", "selective", ""],
    ["USLI", "High School Student Program", "High school juniors", "Wayne, PA", "in-person", "Paid ($17/hr)", "Jan 31", "https://customers.usli.com/sites/studentprogram/high-school-students.html", "finance", "internship", "ineligible", "In-person Pennsylvania.", "selective", ""],
    ["Brooklyn Navy Yard", "Internship Program", "High school seniors", "Brooklyn, NY", "in-person", "Paid (~$16.50/hr)", "Feb 28", "https://www.brooklynnavyyard.org/internship-opportunities/", "business", "internship", "ineligible", "Brooklyn.", "selective", ""],
    ["OneAmerica Financial", "Pathways Junior Fellows", "High school students / recent grads", "Indianapolis, IN", "in-person", "Paid", "January", "https://www.oneamerica.com/about-us/careers/pathways", "finance", "internship", "ineligible", "In-person Indianapolis.", "selective", ""],
    ["Futures and Options", "Internship Program", "Juniors/seniors, 16–19, NYC schools", "New York, NY", "in-person", "Paid", "Jan–Feb", "https://futuresandoptions.org/our-programs/the-internship-program/", "business", "internship", "ineligible", "NYC schools.", "selective", ""],
    ["NYC DYCD", "Ladders for Leaders", "Ages 16–24, NYC", "New York, NY", "in-person", "Paid (~$16.50/hr)", "January", "https://www.nyc.gov/site/dycd/services/jobs-internships/about-nyc-ladders-for-leaders.page", "business", "internship", "ineligible", "NYC residents.", "selective", ""],
  ];

  const typicalKeywords = {
    tech: [K("Python", ["python"], true), K("Programming", ["python", "programming", "coding"], true), K("Problem Solving", ["problem solving"], true), K("Data analysis", ["data analysis", "analytics"]), K("Machine learning / AI", ["machine learning", "ai", "artificial intelligence"]), K("Teamwork", ["team collaboration", "teamwork"]), K("Communication", ["communication"]), K("Self-motivated", ["self-motivated", "self-directed"])],
    research: [K("Research", ["research"], true), K("Data analysis", ["data analysis", "analytics"], true), K("Python", ["python"]), K("Attention to Detail", ["attention to detail"]), K("Problem Solving", ["problem solving"]), K("Self-motivated", ["self-motivated", "self-directed"]), K("Communication", ["communication"])],
    finance: [K("Finance", ["finance", "financial", "business finance"], true), K("Microsoft Excel", ["excel", "spreadsheet"], true), K("Investing / trading", ["trading", "investing", "stock*"], true), K("Technical Analysis", ["technical analysis"]), K("Data analysis", ["data analysis", "analytics"]), K("Communication", ["communication"]), K("Attention to Detail", ["attention to detail"]), K("Time Management", ["time management"])],
    business: [K("Marketing", ["marketing"], true), K("Communication", ["communication"], true), K("Social Media Marketing", ["social media"]), K("Microsoft Office", ["microsoft office", "excel", "powerpoint"]), K("Business", ["business"]), K("Self-motivated", ["self-motivated", "self-directed"]), K("Time Management", ["time management"]), K("Team Collaboration", ["team collaboration", "teamwork"])],
    health: [K("Communication", ["communication"], true), K("Customer service", ["customer service"], true), K("Attention to Detail", ["attention to detail"], true), K("Team Collaboration", ["team collaboration", "teamwork"]), K("Time Management", ["time management"]), K("Research", ["research"]), K("Biology", ["biology"])],
    arts: [K("Photography", ["photography", "photo*"], true), K("Adobe Lightroom", ["lightroom"]), K("Adobe Photoshop", ["photoshop"]), K("Social Media Marketing", ["social media"]), K("Communication", ["communication"], true), K("Portfolio Development", ["portfolio"]), K("Time Management", ["time management"])],
    gov: [K("Communication", ["communication"], true), K("Research", ["research"], true), K("Writing", ["writing"]), K("Microsoft Office", ["microsoft office", "excel"]), K("Attention to Detail", ["attention to detail"]), K("Team Collaboration", ["team collaboration", "teamwork"]), K("Time Management", ["time management"])],
    community: [K("Communication", ["communication"], true), K("Team Collaboration", ["team collaboration", "teamwork"], true), K("Customer service", ["customer service"]), K("Time Management", ["time management"]), K("Self-motivated", ["self-motivated", "self-directed"]), K("Volunteering", ["volunteer*", "community service"])],
  };
  window.TYPICAL_KEYWORDS = typicalKeywords;
  // Interview questions are grouped into three styles.
  const interviewStyle = { tech: "tech", research: "tech", finance: "finance", business: "finance", health: "community", arts: "community", gov: "community", community: "community" };
  const toRate = (r) => (Array.isArray(r) ? { v: r[0], src: "reported", note: r[1] } : { v: RATE_TIERS[r], src: "estimate", tier: r });

  const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  const byOrg = new Map();
  for (const [org, title, elig, loc, mode, pay, deadline, url, field, kind, status, note, rate, about, opens] of rows) {
    const id = "x-" + slug(org);
    if (!byOrg.has(id)) byOrg.set(id, { id, name: org, source: url, roles: [] });
    byOrg.get(id).roles.push({
      id: id + "-" + slug(title),
      title,
      org,
      type: [kind[0].toUpperCase() + kind.slice(1), pay].join(" · "),
      category: interviewStyle[field],
      field,
      kind,
      location: loc,
      mode,
      pay,
      deadline,
      opens: opens || "",
      url,
      elig,
      about: about || "",
      rate: toRate(rate),
      eligibility: { status, reason: `Published eligibility: ${elig}.${note ? " " + note : ""}` },
      keywords: typicalKeywords[field],
    });
  }
  for (const c of byOrg.values()) {
    const r = c.roles[0];
    c.blurb = `${r.location} · ${c.roles.length > 1 ? c.roles.length + " programs" : r.kind}`;
  }

  // Details for the hand-written entries in companies.js: [location, mode, pay, field, kind, deadline, rate, about, opens]
  const meta = {
    "sdcity-ee": ["San Diego, CA", "in-person", "Paid", "gov", "internship", "Spring", "moderate", "Paid internships in city departments (finance, IT, library, public health and more) for California youth 16–30."],
    "sdsc-rehs": ["La Jolla, CA", "in-person", "Unpaid", "tech", "research", "Spring", "selective", "Summer research at the San Diego Supercomputer Center — you're paired with a mentor and join a computational research team."],
    "bofa-leaders": ["San Diego, CA + Washington, DC", "in-person", "Paid", "community", "internship", "Oct–Jan", "competitive", "8 weeks of paid work at a local nonprofit plus a leadership summit in Washington, DC.", "Oct"],
    "bofa-analyst": ["Multiple", "in-person", "Paid", "finance", "internship", "Varies", "elite", ""],
    "gs-analyst": ["Multiple", "in-person", "Paid", "finance", "internship", "Varies", "elite", ""],
    "nasa-ostem": ["NASA centers / remote", "hybrid", "Paid", "tech", "internship", "Feb / May / Sep", "competitive", ""],
    "qc-eng": ["San Diego, CA", "in-person", "Paid", "tech", "internship", "Fall", "competitive", ""],
    "c2c-youth": ["San Diego, CA", "in-person", "Paid", "community", "internship", "April", "moderate", ""],
    "ladder-startup": ["Remote", "remote", "Fee (aid available)", "business", "internship", "Multiple cohorts", "moderate", "8–12 week remote internship at a startup or nonprofit, matched through Ladder. Costs around $2,000+ with financial aid."],
  };
  for (const c of COMPANIES)
    for (const r of c.roles)
      if (meta[r.id]) {
        const [location, mode, pay, field, kind, deadline, rate, about, opens] = meta[r.id];
        Object.assign(r, { org: c.name, location, mode, pay, field, kind, deadline, opens: opens || "", about, rate: toRate(rate), url: r.url || c.source, elig: r.eligibility.reason });
      }

  // Merge into a hand-written company when the organization already exists (e.g. NASA, City of San Diego).
  for (const c of byOrg.values()) {
    const existing = COMPANIES.find((x) => x.name.toLowerCase() === c.name.toLowerCase());
    if (existing) existing.roles.push(...c.roles);
    else COMPANIES.push(c);
  }
})();
